### ISSUE TITLE
.... with button 

### ISSUE THREAD

**Issue by saikle** [Klapautsiy/titanium-bicycle-for-button#1]
бред...

**Comment by saikle** [comment]
Нужно синхронизировать состояния кнопок при Mqtt. У меня с библиотекой вроде 12.00 работает arduino уже под года без подтягивающих резисторов. Одна нога на разъём (А0 например), вторая на gnd. В прикрепленом файле брокеру mqtt непрерывно шлется состояние 0,1( очень быстро меняется). Спасибо вам за библиотеку. Ее функции можно использовать для управления всем домом. Предполагаю если удастся решить проблему, на долгое нажатие одной из кнопок повесить событие "я ушёл", чтобы выключить все в доме. На другой можно повесить тихий режим. В коде для подключения к брокеру используется delay. У вас используются таймеры. Может из за этого ? Как тогда заменить?

**Comment by saikle** [comment]
Ошибка наверно из за того, что пропала функция apartment.duration_timer_Dn      (500);  С ней не компилируется. Посмотрел точно — раньше использовал библиотеки 10.0.

**Comment by Klapautsiy** [comment]
отправь мне код с твоего первого поста на любой ресурс, кроме вражеского - гуглдрайв или дропбокс, например.

**Comment by saikle** [comment]
Из первого поста https://drive.google.com/open?id=1S8JT7bP1qXzsVQual9LX4g1l18mKU8Vj
Это простой пример для новых библиотек https://drive.google.com/open?id=1gn-C8KHh_NwUP5zYkmiqi1pmJ89JTrvH
Раньше, когда кнопка записывалась так apartment.button[0].event_click_Dn() == 1) Этот простой пример работал.
Поэтому из первого поста можно не смотреть, а посмотреть простой пример из второй ссылки в этом посте. Может  у вас остались библиотеки версии 10.0 ? Если да, тогда вопрос будет решён.

**Comment by Klapautsiy** [comment]
дать тебе версию 10.0, что бы ты юзал непритянутую резистором к Gnd кнопку - оказать тебе медвежью услугу.
фича, которую ты обнаружил в версии 10.0, когда пин кнопки перед опросом его состояния какое-то время находится в состоянии логический 0, и может, в некоторых очень частных случаях, заменить подтяжку пина резистором, аппаратно зависит от типа, возможно, ревизии контроллера.
документировать эту фичу мне не представляется возможным, рекомендовать её пользователям -
 считаю безответственным поступком со своей стороны.

поэтому, поступай, как написано в файле README.txt 10.0-й и последующих версиях:

```
при активации режима pullDn, подключение пинов кнопок к GND через резисторы
10KOm обязательно
```

**Comment by saikle** [comment]
Мне сейчас времено проще сделать так. Если ты не рекомендуешь, а пользователь использует, то ты за это не отвечаешь. Прошу, скинь, пожалуйста, на почту r9301019141@gmail.com версию 10.00. Я задоначу тебе.

**Comment by saikle** [comment]
У меня потому что нет сейчас нормальных резисторов. Подключаю эти Из комплекта 
https://www.aliexpress.com/item/32550078872/32550078872.html
Дребезг пропадает, но и реакции никакой

**Comment by saikle** [comment]
Я pulldn не активировал и дребезг все равно был. Я так понимаю, что твоя библиотека может работать без подтягивающего резистора

**Comment by saikle** [comment]
Мне нужна библиотека без подтяжки и я готов заплатить

**Comment by Klapautsiy** [comment]
отправил на указанную тобой почту версию 10.0
претензии к её работе не принимаются.

**Comment by Klapautsiy** [comment]
всё, выше написанное о якобы фиче, прошу считать практически не подтвердившимся предположением.

**Comment by Klapautsiy** [comment]
ччч
